package com.ufgov.zc.common.zc.model;

public class ZcBrand extends ZcBaseBill{
    /**
   * 
   */
  private static final long serialVersionUID = -6505185087658747446L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_BRAND.BRAND_CODE
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    private String brandCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_BRAND.BRAND_NAME
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_BRAND.LINK_MAN
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    private String linkMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_BRAND.LINK_TEL
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    private String linkTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_BRAND.LINK_MOBILE
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    private String linkMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_BRAND.LINK_FAX
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    private String linkFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_BRAND.LINK_ADDRESS
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    private String linkAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_BRAND.IS_ENABLE
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    private String isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_BRAND.BRAND_CODE
     *
     * @return the value of ZC_BRAND.BRAND_CODE
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public String getBrandCode() {
        return brandCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_BRAND.BRAND_CODE
     *
     * @param brandCode the value for ZC_BRAND.BRAND_CODE
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public void setBrandCode(String brandCode) {
        this.brandCode = brandCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_BRAND.BRAND_NAME
     *
     * @return the value of ZC_BRAND.BRAND_NAME
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_BRAND.BRAND_NAME
     *
     * @param brandName the value for ZC_BRAND.BRAND_NAME
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_BRAND.LINK_MAN
     *
     * @return the value of ZC_BRAND.LINK_MAN
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_BRAND.LINK_MAN
     *
     * @param linkMan the value for ZC_BRAND.LINK_MAN
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_BRAND.LINK_TEL
     *
     * @return the value of ZC_BRAND.LINK_TEL
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public String getLinkTel() {
        return linkTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_BRAND.LINK_TEL
     *
     * @param linkTel the value for ZC_BRAND.LINK_TEL
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public void setLinkTel(String linkTel) {
        this.linkTel = linkTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_BRAND.LINK_MOBILE
     *
     * @return the value of ZC_BRAND.LINK_MOBILE
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public String getLinkMobile() {
        return linkMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_BRAND.LINK_MOBILE
     *
     * @param linkMobile the value for ZC_BRAND.LINK_MOBILE
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public void setLinkMobile(String linkMobile) {
        this.linkMobile = linkMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_BRAND.LINK_FAX
     *
     * @return the value of ZC_BRAND.LINK_FAX
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public String getLinkFax() {
        return linkFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_BRAND.LINK_FAX
     *
     * @param linkFax the value for ZC_BRAND.LINK_FAX
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public void setLinkFax(String linkFax) {
        this.linkFax = linkFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_BRAND.LINK_ADDRESS
     *
     * @return the value of ZC_BRAND.LINK_ADDRESS
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public String getLinkAddress() {
        return linkAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_BRAND.LINK_ADDRESS
     *
     * @param linkAddress the value for ZC_BRAND.LINK_ADDRESS
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public void setLinkAddress(String linkAddress) {
        this.linkAddress = linkAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_BRAND.IS_ENABLE
     *
     * @return the value of ZC_BRAND.IS_ENABLE
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_BRAND.IS_ENABLE
     *
     * @param isEnable the value for ZC_BRAND.IS_ENABLE
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }
}