package com.ufgov.zc.common.zc.model;

import java.math.BigDecimal;

public class ZcDingdianItem extends ZcBaseBill{
  
  public static final String COL_DD_CODE="ZC_DINGDIAN_ITEM_DD_CODE"; // 定点编号
  public static final String COL_DD_ITEM_CODE="ZC_DINGDIAN_ITEM_DD_ITEM_CODE"; // 定点明细编号
  public static final String COL_ITEM_BI="ZC_DINGDIAN_ITEM_ITEM_BI"; // 实际财政资金 
  public static final String COL_ITEM_CONTENT="ZC_DINGDIAN_ITEM_ITEM_CONTENT"; // 采购项目
  public static final String COL_ITEM_DETAIL="ZC_DINGDIAN_ITEM_ITEM_DETAIL"; // 明细
  public static final String COL_ITEM_OTHER="ZC_DINGDIAN_ITEM_ITEM_OTHER"; // 实际其他资金 
  public static final String COL_ITEM_TOTAL_SUM="ZC_DINGDIAN_ITEM_ITEM_TOTAL_SUM"; // 总价
  public static final String COL_ITEM_TYPE="ZC_DINGDIAN_ITEM_ITEM_TYPE"; // 服务类别
  public static final String COL_ITEM_VAL="ZC_DINGDIAN_ITEM_ITEM_VAL"; // 实际金额
  public static final String COL_REMARK="ZC_DINGDIAN_ITEM_REMARK"; // 备注
  public static final String COL_MER_CODE="ZC_DINGDIAN_ITEM_MER_CODE"; // 商品编号
  public static final String COL_MER_PRICE="ZC_DINGDIAN_ITEM_MER_PRICE"; // 商品价格
  public static final String COL_MER_NUM="ZC_DINGDIAN_ITEM_MER_NUM"; // 采购数量

  private String merCode;
  private BigDecimal merPrice;
  private BigDecimal merNum;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_ITEM.DD_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    private String ddCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_ITEM.DD_ITEM_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    private String ddItemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_ITEM.ITEM_CONTENT
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    private String itemContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_ITEM.REMARK
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_ITEM.ITEM_TOTAL_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    private BigDecimal itemTotalSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_ITEM.ITEM_VAL
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    private BigDecimal itemVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_ITEM.ITEM_BI
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    private BigDecimal itemBi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_ITEM.ITEM_OTHER
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    private BigDecimal itemOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_ITEM.ITEM_TYPE
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    private String itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_ITEM.ITEM_DETAIL
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    private String itemDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_ITEM.DD_CODE
     *
     * @return the value of ZC_DINGDIAN_ITEM.DD_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public String getDdCode() {
        return ddCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_ITEM.DD_CODE
     *
     * @param ddCode the value for ZC_DINGDIAN_ITEM.DD_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public void setDdCode(String ddCode) {
        this.ddCode = ddCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_ITEM.DD_ITEM_CODE
     *
     * @return the value of ZC_DINGDIAN_ITEM.DD_ITEM_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public String getDdItemCode() {
        return ddItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_ITEM.DD_ITEM_CODE
     *
     * @param ddItemCode the value for ZC_DINGDIAN_ITEM.DD_ITEM_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public void setDdItemCode(String ddItemCode) {
        this.ddItemCode = ddItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_ITEM.ITEM_CONTENT
     *
     * @return the value of ZC_DINGDIAN_ITEM.ITEM_CONTENT
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public String getItemContent() {
        return itemContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_ITEM.ITEM_CONTENT
     *
     * @param itemContent the value for ZC_DINGDIAN_ITEM.ITEM_CONTENT
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public void setItemContent(String itemContent) {
        this.itemContent = itemContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_ITEM.REMARK
     *
     * @return the value of ZC_DINGDIAN_ITEM.REMARK
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_ITEM.REMARK
     *
     * @param remark the value for ZC_DINGDIAN_ITEM.REMARK
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_ITEM.ITEM_TOTAL_SUM
     *
     * @return the value of ZC_DINGDIAN_ITEM.ITEM_TOTAL_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public BigDecimal getItemTotalSum() {
        return itemTotalSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_ITEM.ITEM_TOTAL_SUM
     *
     * @param itemTotalSum the value for ZC_DINGDIAN_ITEM.ITEM_TOTAL_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public void setItemTotalSum(BigDecimal itemTotalSum) {
        this.itemTotalSum = itemTotalSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_ITEM.ITEM_VAL
     *
     * @return the value of ZC_DINGDIAN_ITEM.ITEM_VAL
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public BigDecimal getItemVal() {
        return itemVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_ITEM.ITEM_VAL
     *
     * @param itemVal the value for ZC_DINGDIAN_ITEM.ITEM_VAL
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public void setItemVal(BigDecimal itemVal) {
        this.itemVal = itemVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_ITEM.ITEM_BI
     *
     * @return the value of ZC_DINGDIAN_ITEM.ITEM_BI
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public BigDecimal getItemBi() {
        return itemBi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_ITEM.ITEM_BI
     *
     * @param itemBi the value for ZC_DINGDIAN_ITEM.ITEM_BI
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public void setItemBi(BigDecimal itemBi) {
        this.itemBi = itemBi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_ITEM.ITEM_OTHER
     *
     * @return the value of ZC_DINGDIAN_ITEM.ITEM_OTHER
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public BigDecimal getItemOther() {
        return itemOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_ITEM.ITEM_OTHER
     *
     * @param itemOther the value for ZC_DINGDIAN_ITEM.ITEM_OTHER
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public void setItemOther(BigDecimal itemOther) {
        this.itemOther = itemOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_ITEM.ITEM_TYPE
     *
     * @return the value of ZC_DINGDIAN_ITEM.ITEM_TYPE
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_ITEM.ITEM_TYPE
     *
     * @param itemType the value for ZC_DINGDIAN_ITEM.ITEM_TYPE
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_ITEM.ITEM_DETAIL
     *
     * @return the value of ZC_DINGDIAN_ITEM.ITEM_DETAIL
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public String getItemDetail() {
        return itemDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_ITEM.ITEM_DETAIL
     *
     * @param itemDetail the value for ZC_DINGDIAN_ITEM.ITEM_DETAIL
     *
     * @mbggenerated Wed Feb 03 14:06:35 CST 2016
     */
    public void setItemDetail(String itemDetail) {
        this.itemDetail = itemDetail;
    }

    public String getMerCode() {
      return merCode;
    }

    public void setMerCode(String mercode) {
      this.merCode = mercode;
    }

    public BigDecimal getMerPrice() {
      return merPrice;
    }

    public void setMerPrice(BigDecimal merPrice) {
      this.merPrice = merPrice;
    }

    public BigDecimal getMerNum() {
      return merNum;
    }

    public void setMerNum(BigDecimal merNum) {
      this.merNum = merNum;
    }
}