package com.ufgov.zc.common.zc.model;

import java.math.BigDecimal;

public class ZcDingdianBi extends ZcBaseBill{

  
  /**
   * 财政预算
   */
  public static final String TYPE_CZYS="01";
  /**
   * 自筹资金
   */
  public static final String TYPE_ZCZJ="02";

  private String tempId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.DD_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String ddCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_BI_NO
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcBiNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_BI_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private BigDecimal zcBiSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_BI_JHUA_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private BigDecimal zcBiJhuaSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_BI_DO_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private BigDecimal zcBiDoSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_BI_YJBA_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private BigDecimal zcBiYjbaSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.BI_TARGET_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String biTargetCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.B_ACC_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String bAccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.B_ACC_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String bAccName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.CO_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String coCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.CO_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String coName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.DEC_MONEY
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private BigDecimal decMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.FUND_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String fundCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.FUND_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String fundName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.INCEPTDOC_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String inceptdocCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.INCEPTDOC_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String inceptdocName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.MANAGE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String manageCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.MANAGE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String manageName;
 
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ORG_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ORG_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ORIGIN_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String originCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ORIGIN_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String originName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.OUTLAY_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String outlayCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.OUTLAY_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String outlayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.PAYOUT_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String payoutCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.PAYOUT_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String payoutName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.PAYTYPE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String paytypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.PAYTYPE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String paytypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.PROJECT_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.PROJECT_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.PROJECT_TYPE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String projectTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.PROJECT_TYPE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String projectTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.SENDDOC_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String senddocCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.SENDDOC_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String senddocName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.SENDDOC_TYPE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String senddocTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.SENDDOC_TYPE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String senddocTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_BI_HTBA_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private BigDecimal zcBiHtbaSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_CG_TYPE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcCgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_PLAN_TYPE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcPlanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_SAVE_NUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private BigDecimal zcSaveNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_CATALOGUE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcCatalogueCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_CATALOGUE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcCatalogueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_YEAR
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_YEP_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private BigDecimal zcYepSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_BI_APD_FLAG
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcBiApdFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_FUND_REMARK
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcFundRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_FUND_FILE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcFundFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_FUND_FILE_BLOBID
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcFundFileBlobid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.IS_ADD_ONFUNDS
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String isAddOnfunds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.SUPPLEMENT_AMOUNT
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private BigDecimal supplementAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_PRO_BI_SEQ
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcProBiSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_USE_BI_ID
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcUseBiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_ZJ_TYPE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcZjType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_AM_BILL_NO
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcAmBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_BIS_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcBisCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.ZC_BIS_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String zcBisName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.OUT_LAY_IS_LEAF
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String outLayIsLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.GB_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String gbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_DINGDIAN_BI.BT_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    private String btName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.DD_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.DD_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getDdCode() {
        return ddCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.DD_CODE
     *
     * @param ddCode the value for ZC_DINGDIAN_BI.DD_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setDdCode(String ddCode) {
        this.ddCode = ddCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_BI_NO
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_BI_NO
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcBiNo() {
        return zcBiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_BI_NO
     *
     * @param zcBiNo the value for ZC_DINGDIAN_BI.ZC_BI_NO
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcBiNo(String zcBiNo) {
        this.zcBiNo = zcBiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_BI_SUM
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_BI_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public BigDecimal getZcBiSum() {
        return zcBiSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_BI_SUM
     *
     * @param zcBiSum the value for ZC_DINGDIAN_BI.ZC_BI_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcBiSum(BigDecimal zcBiSum) {
        this.zcBiSum = zcBiSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_BI_JHUA_SUM
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_BI_JHUA_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public BigDecimal getZcBiJhuaSum() {
        return zcBiJhuaSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_BI_JHUA_SUM
     *
     * @param zcBiJhuaSum the value for ZC_DINGDIAN_BI.ZC_BI_JHUA_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcBiJhuaSum(BigDecimal zcBiJhuaSum) {
        this.zcBiJhuaSum = zcBiJhuaSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_BI_DO_SUM
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_BI_DO_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public BigDecimal getZcBiDoSum() {
        return zcBiDoSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_BI_DO_SUM
     *
     * @param zcBiDoSum the value for ZC_DINGDIAN_BI.ZC_BI_DO_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcBiDoSum(BigDecimal zcBiDoSum) {
        this.zcBiDoSum = zcBiDoSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_BI_YJBA_SUM
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_BI_YJBA_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public BigDecimal getZcBiYjbaSum() {
        return zcBiYjbaSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_BI_YJBA_SUM
     *
     * @param zcBiYjbaSum the value for ZC_DINGDIAN_BI.ZC_BI_YJBA_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcBiYjbaSum(BigDecimal zcBiYjbaSum) {
        this.zcBiYjbaSum = zcBiYjbaSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.BI_TARGET_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.BI_TARGET_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getBiTargetCode() {
        return biTargetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.BI_TARGET_CODE
     *
     * @param biTargetCode the value for ZC_DINGDIAN_BI.BI_TARGET_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setBiTargetCode(String biTargetCode) {
        this.biTargetCode = biTargetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.B_ACC_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.B_ACC_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getbAccCode() {
        return bAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.B_ACC_CODE
     *
     * @param bAccCode the value for ZC_DINGDIAN_BI.B_ACC_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setbAccCode(String bAccCode) {
        this.bAccCode = bAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.B_ACC_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.B_ACC_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getbAccName() {
        return bAccName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.B_ACC_NAME
     *
     * @param bAccName the value for ZC_DINGDIAN_BI.B_ACC_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setbAccName(String bAccName) {
        this.bAccName = bAccName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.CO_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.CO_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getCoCode() {
        return coCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.CO_CODE
     *
     * @param coCode the value for ZC_DINGDIAN_BI.CO_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setCoCode(String coCode) {
        this.coCode = coCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.CO_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.CO_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getCoName() {
        return coName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.CO_NAME
     *
     * @param coName the value for ZC_DINGDIAN_BI.CO_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setCoName(String coName) {
        this.coName = coName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.DEC_MONEY
     *
     * @return the value of ZC_DINGDIAN_BI.DEC_MONEY
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public BigDecimal getDecMoney() {
        return decMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.DEC_MONEY
     *
     * @param decMoney the value for ZC_DINGDIAN_BI.DEC_MONEY
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setDecMoney(BigDecimal decMoney) {
        this.decMoney = decMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.FUND_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.FUND_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.FUND_CODE
     *
     * @param fundCode the value for ZC_DINGDIAN_BI.FUND_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.FUND_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.FUND_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.FUND_NAME
     *
     * @param fundName the value for ZC_DINGDIAN_BI.FUND_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setFundName(String fundName) {
        this.fundName = fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.INCEPTDOC_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.INCEPTDOC_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getInceptdocCode() {
        return inceptdocCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.INCEPTDOC_CODE
     *
     * @param inceptdocCode the value for ZC_DINGDIAN_BI.INCEPTDOC_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setInceptdocCode(String inceptdocCode) {
        this.inceptdocCode = inceptdocCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.INCEPTDOC_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.INCEPTDOC_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getInceptdocName() {
        return inceptdocName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.INCEPTDOC_NAME
     *
     * @param inceptdocName the value for ZC_DINGDIAN_BI.INCEPTDOC_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setInceptdocName(String inceptdocName) {
        this.inceptdocName = inceptdocName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.MANAGE_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.MANAGE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getManageCode() {
        return manageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.MANAGE_CODE
     *
     * @param manageCode the value for ZC_DINGDIAN_BI.MANAGE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setManageCode(String manageCode) {
        this.manageCode = manageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.MANAGE_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.MANAGE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getManageName() {
        return manageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.MANAGE_NAME
     *
     * @param manageName the value for ZC_DINGDIAN_BI.MANAGE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setManageName(String manageName) {
        this.manageName = manageName;
    }

 

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ORG_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.ORG_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ORG_CODE
     *
     * @param orgCode the value for ZC_DINGDIAN_BI.ORG_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ORG_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.ORG_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ORG_NAME
     *
     * @param orgName the value for ZC_DINGDIAN_BI.ORG_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ORIGIN_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.ORIGIN_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getOriginCode() {
        return originCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ORIGIN_CODE
     *
     * @param originCode the value for ZC_DINGDIAN_BI.ORIGIN_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setOriginCode(String originCode) {
        this.originCode = originCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ORIGIN_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.ORIGIN_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getOriginName() {
        return originName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ORIGIN_NAME
     *
     * @param originName the value for ZC_DINGDIAN_BI.ORIGIN_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setOriginName(String originName) {
        this.originName = originName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.OUTLAY_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.OUTLAY_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getOutlayCode() {
        return outlayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.OUTLAY_CODE
     *
     * @param outlayCode the value for ZC_DINGDIAN_BI.OUTLAY_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setOutlayCode(String outlayCode) {
        this.outlayCode = outlayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.OUTLAY_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.OUTLAY_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getOutlayName() {
        return outlayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.OUTLAY_NAME
     *
     * @param outlayName the value for ZC_DINGDIAN_BI.OUTLAY_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setOutlayName(String outlayName) {
        this.outlayName = outlayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.PAYOUT_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.PAYOUT_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getPayoutCode() {
        return payoutCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.PAYOUT_CODE
     *
     * @param payoutCode the value for ZC_DINGDIAN_BI.PAYOUT_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setPayoutCode(String payoutCode) {
        this.payoutCode = payoutCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.PAYOUT_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.PAYOUT_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getPayoutName() {
        return payoutName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.PAYOUT_NAME
     *
     * @param payoutName the value for ZC_DINGDIAN_BI.PAYOUT_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setPayoutName(String payoutName) {
        this.payoutName = payoutName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.PAYTYPE_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.PAYTYPE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getPaytypeCode() {
        return paytypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.PAYTYPE_CODE
     *
     * @param paytypeCode the value for ZC_DINGDIAN_BI.PAYTYPE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setPaytypeCode(String paytypeCode) {
        this.paytypeCode = paytypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.PAYTYPE_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.PAYTYPE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getPaytypeName() {
        return paytypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.PAYTYPE_NAME
     *
     * @param paytypeName the value for ZC_DINGDIAN_BI.PAYTYPE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setPaytypeName(String paytypeName) {
        this.paytypeName = paytypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.PROJECT_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.PROJECT_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.PROJECT_CODE
     *
     * @param projectCode the value for ZC_DINGDIAN_BI.PROJECT_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.PROJECT_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.PROJECT_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.PROJECT_NAME
     *
     * @param projectName the value for ZC_DINGDIAN_BI.PROJECT_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.PROJECT_TYPE_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.PROJECT_TYPE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getProjectTypeCode() {
        return projectTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.PROJECT_TYPE_CODE
     *
     * @param projectTypeCode the value for ZC_DINGDIAN_BI.PROJECT_TYPE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setProjectTypeCode(String projectTypeCode) {
        this.projectTypeCode = projectTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.PROJECT_TYPE_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.PROJECT_TYPE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getProjectTypeName() {
        return projectTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.PROJECT_TYPE_NAME
     *
     * @param projectTypeName the value for ZC_DINGDIAN_BI.PROJECT_TYPE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setProjectTypeName(String projectTypeName) {
        this.projectTypeName = projectTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.SENDDOC_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.SENDDOC_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getSenddocCode() {
        return senddocCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.SENDDOC_CODE
     *
     * @param senddocCode the value for ZC_DINGDIAN_BI.SENDDOC_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setSenddocCode(String senddocCode) {
        this.senddocCode = senddocCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.SENDDOC_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.SENDDOC_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getSenddocName() {
        return senddocName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.SENDDOC_NAME
     *
     * @param senddocName the value for ZC_DINGDIAN_BI.SENDDOC_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setSenddocName(String senddocName) {
        this.senddocName = senddocName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.SENDDOC_TYPE_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.SENDDOC_TYPE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getSenddocTypeCode() {
        return senddocTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.SENDDOC_TYPE_CODE
     *
     * @param senddocTypeCode the value for ZC_DINGDIAN_BI.SENDDOC_TYPE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setSenddocTypeCode(String senddocTypeCode) {
        this.senddocTypeCode = senddocTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.SENDDOC_TYPE_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.SENDDOC_TYPE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getSenddocTypeName() {
        return senddocTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.SENDDOC_TYPE_NAME
     *
     * @param senddocTypeName the value for ZC_DINGDIAN_BI.SENDDOC_TYPE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setSenddocTypeName(String senddocTypeName) {
        this.senddocTypeName = senddocTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_BI_HTBA_SUM
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_BI_HTBA_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public BigDecimal getZcBiHtbaSum() {
        return zcBiHtbaSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_BI_HTBA_SUM
     *
     * @param zcBiHtbaSum the value for ZC_DINGDIAN_BI.ZC_BI_HTBA_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcBiHtbaSum(BigDecimal zcBiHtbaSum) {
        this.zcBiHtbaSum = zcBiHtbaSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_CG_TYPE
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_CG_TYPE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcCgType() {
        return zcCgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_CG_TYPE
     *
     * @param zcCgType the value for ZC_DINGDIAN_BI.ZC_CG_TYPE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcCgType(String zcCgType) {
        this.zcCgType = zcCgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_PLAN_TYPE
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_PLAN_TYPE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcPlanType() {
        return zcPlanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_PLAN_TYPE
     *
     * @param zcPlanType the value for ZC_DINGDIAN_BI.ZC_PLAN_TYPE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcPlanType(String zcPlanType) {
        this.zcPlanType = zcPlanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_SAVE_NUM
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_SAVE_NUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public BigDecimal getZcSaveNum() {
        return zcSaveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_SAVE_NUM
     *
     * @param zcSaveNum the value for ZC_DINGDIAN_BI.ZC_SAVE_NUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcSaveNum(BigDecimal zcSaveNum) {
        this.zcSaveNum = zcSaveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_CATALOGUE_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_CATALOGUE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcCatalogueCode() {
        return zcCatalogueCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_CATALOGUE_CODE
     *
     * @param zcCatalogueCode the value for ZC_DINGDIAN_BI.ZC_CATALOGUE_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcCatalogueCode(String zcCatalogueCode) {
        this.zcCatalogueCode = zcCatalogueCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_CATALOGUE_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_CATALOGUE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcCatalogueName() {
        return zcCatalogueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_CATALOGUE_NAME
     *
     * @param zcCatalogueName the value for ZC_DINGDIAN_BI.ZC_CATALOGUE_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcCatalogueName(String zcCatalogueName) {
        this.zcCatalogueName = zcCatalogueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_YEAR
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_YEAR
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcYear() {
        return zcYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_YEAR
     *
     * @param zcYear the value for ZC_DINGDIAN_BI.ZC_YEAR
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcYear(String zcYear) {
        this.zcYear = zcYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_YEP_SUM
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_YEP_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public BigDecimal getZcYepSum() {
        return zcYepSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_YEP_SUM
     *
     * @param zcYepSum the value for ZC_DINGDIAN_BI.ZC_YEP_SUM
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcYepSum(BigDecimal zcYepSum) {
        this.zcYepSum = zcYepSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_BI_APD_FLAG
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_BI_APD_FLAG
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcBiApdFlag() {
        return zcBiApdFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_BI_APD_FLAG
     *
     * @param zcBiApdFlag the value for ZC_DINGDIAN_BI.ZC_BI_APD_FLAG
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcBiApdFlag(String zcBiApdFlag) {
        this.zcBiApdFlag = zcBiApdFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_FUND_REMARK
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_FUND_REMARK
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcFundRemark() {
        return zcFundRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_FUND_REMARK
     *
     * @param zcFundRemark the value for ZC_DINGDIAN_BI.ZC_FUND_REMARK
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcFundRemark(String zcFundRemark) {
        this.zcFundRemark = zcFundRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_FUND_FILE
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_FUND_FILE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcFundFile() {
        return zcFundFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_FUND_FILE
     *
     * @param zcFundFile the value for ZC_DINGDIAN_BI.ZC_FUND_FILE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcFundFile(String zcFundFile) {
        this.zcFundFile = zcFundFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_FUND_FILE_BLOBID
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_FUND_FILE_BLOBID
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcFundFileBlobid() {
        return zcFundFileBlobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_FUND_FILE_BLOBID
     *
     * @param zcFundFileBlobid the value for ZC_DINGDIAN_BI.ZC_FUND_FILE_BLOBID
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcFundFileBlobid(String zcFundFileBlobid) {
        this.zcFundFileBlobid = zcFundFileBlobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.IS_ADD_ONFUNDS
     *
     * @return the value of ZC_DINGDIAN_BI.IS_ADD_ONFUNDS
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getIsAddOnfunds() {
        return isAddOnfunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.IS_ADD_ONFUNDS
     *
     * @param isAddOnfunds the value for ZC_DINGDIAN_BI.IS_ADD_ONFUNDS
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setIsAddOnfunds(String isAddOnfunds) {
        this.isAddOnfunds = isAddOnfunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.SUPPLEMENT_AMOUNT
     *
     * @return the value of ZC_DINGDIAN_BI.SUPPLEMENT_AMOUNT
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public BigDecimal getSupplementAmount() {
        return supplementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.SUPPLEMENT_AMOUNT
     *
     * @param supplementAmount the value for ZC_DINGDIAN_BI.SUPPLEMENT_AMOUNT
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setSupplementAmount(BigDecimal supplementAmount) {
        this.supplementAmount = supplementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_PRO_BI_SEQ
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_PRO_BI_SEQ
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcProBiSeq() {
        return zcProBiSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_PRO_BI_SEQ
     *
     * @param zcProBiSeq the value for ZC_DINGDIAN_BI.ZC_PRO_BI_SEQ
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcProBiSeq(String zcProBiSeq) {
        this.zcProBiSeq = zcProBiSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_USE_BI_ID
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_USE_BI_ID
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcUseBiId() {
        return zcUseBiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_USE_BI_ID
     *
     * @param zcUseBiId the value for ZC_DINGDIAN_BI.ZC_USE_BI_ID
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcUseBiId(String zcUseBiId) {
        this.zcUseBiId = zcUseBiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_ZJ_TYPE
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_ZJ_TYPE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcZjType() {
        return zcZjType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_ZJ_TYPE
     *
     * @param zcZjType the value for ZC_DINGDIAN_BI.ZC_ZJ_TYPE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcZjType(String zcZjType) {
        this.zcZjType = zcZjType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_AM_BILL_NO
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_AM_BILL_NO
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcAmBillNo() {
        return zcAmBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_AM_BILL_NO
     *
     * @param zcAmBillNo the value for ZC_DINGDIAN_BI.ZC_AM_BILL_NO
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcAmBillNo(String zcAmBillNo) {
        this.zcAmBillNo = zcAmBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_BIS_CODE
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_BIS_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcBisCode() {
        return zcBisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_BIS_CODE
     *
     * @param zcBisCode the value for ZC_DINGDIAN_BI.ZC_BIS_CODE
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcBisCode(String zcBisCode) {
        this.zcBisCode = zcBisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.ZC_BIS_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.ZC_BIS_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getZcBisName() {
        return zcBisName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.ZC_BIS_NAME
     *
     * @param zcBisName the value for ZC_DINGDIAN_BI.ZC_BIS_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setZcBisName(String zcBisName) {
        this.zcBisName = zcBisName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.OUT_LAY_IS_LEAF
     *
     * @return the value of ZC_DINGDIAN_BI.OUT_LAY_IS_LEAF
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getOutLayIsLeaf() {
        return outLayIsLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.OUT_LAY_IS_LEAF
     *
     * @param outLayIsLeaf the value for ZC_DINGDIAN_BI.OUT_LAY_IS_LEAF
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setOutLayIsLeaf(String outLayIsLeaf) {
        this.outLayIsLeaf = outLayIsLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.GB_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.GB_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getGbName() {
        return gbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.GB_NAME
     *
     * @param gbName the value for ZC_DINGDIAN_BI.GB_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setGbName(String gbName) {
        this.gbName = gbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_DINGDIAN_BI.BT_NAME
     *
     * @return the value of ZC_DINGDIAN_BI.BT_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public String getBtName() {
        return btName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_DINGDIAN_BI.BT_NAME
     *
     * @param btName the value for ZC_DINGDIAN_BI.BT_NAME
     *
     * @mbggenerated Wed Feb 03 14:06:17 CST 2016
     */
    public void setBtName(String btName) {
        this.btName = btName;
    }

    public String getTempId() {
      return tempId;
    }

    public void setTempId(String tempId) {
      this.tempId = tempId;
    }
}