package com.ufgov.zc.common.zc.model;

public class ZcGoodsSpec extends ZcGoodsSpecKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_SPEC.SPEC
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    private String spec;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_SPEC.SPEC
     *
     * @return the value of ZC_GOODS_SPEC.SPEC
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_SPEC.SPEC
     *
     * @param spec the value for ZC_GOODS_SPEC.SPEC
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    public void setSpec(String spec) {
        this.spec = spec;
    }
}