package com.ufgov.zc.common.zc.model;

public class ZcGoodsImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_IMAGE.GOODS_CODE
     *
     * @mbggenerated Tue Jan 19 22:27:56 CST 2016
     */
    private String goodsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_IMAGE.IMAGE_ID
     *
     * @mbggenerated Tue Jan 19 22:27:56 CST 2016
     */
    private String imageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_IMAGE.GOODS_CODE
     *
     * @return the value of ZC_GOODS_IMAGE.GOODS_CODE
     *
     * @mbggenerated Tue Jan 19 22:27:56 CST 2016
     */
    public String getGoodsCode() {
        return goodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_IMAGE.GOODS_CODE
     *
     * @param goodsCode the value for ZC_GOODS_IMAGE.GOODS_CODE
     *
     * @mbggenerated Tue Jan 19 22:27:56 CST 2016
     */
    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_IMAGE.IMAGE_ID
     *
     * @return the value of ZC_GOODS_IMAGE.IMAGE_ID
     *
     * @mbggenerated Tue Jan 19 22:27:56 CST 2016
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_IMAGE.IMAGE_ID
     *
     * @param imageId the value for ZC_GOODS_IMAGE.IMAGE_ID
     *
     * @mbggenerated Tue Jan 19 22:27:56 CST 2016
     */
    public void setImageId(String imageId) {
        this.imageId = imageId;
    }
}