package com.ufgov.zc.common.zc.model;

public class ZcGoodsSpecKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_SPEC.GOODS_CODE
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    private String goodsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_SPEC.SPEC_CODE
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    private String specCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_SPEC.GOODS_CODE
     *
     * @return the value of ZC_GOODS_SPEC.GOODS_CODE
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    public String getGoodsCode() {
        return goodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_SPEC.GOODS_CODE
     *
     * @param goodsCode the value for ZC_GOODS_SPEC.GOODS_CODE
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_SPEC.SPEC_CODE
     *
     * @return the value of ZC_GOODS_SPEC.SPEC_CODE
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    public String getSpecCode() {
        return specCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_SPEC.SPEC_CODE
     *
     * @param specCode the value for ZC_GOODS_SPEC.SPEC_CODE
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    public void setSpecCode(String specCode) {
        this.specCode = specCode;
    }
}