package com.ufgov.zc.common.zc.model;

import java.math.BigDecimal;

public class ZcGoodsSpecTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_CODE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    private String specCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_NAME
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    private String specName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_PARENT_CODE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    private String specParentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_SHOW_INDEX
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    private BigDecimal specShowIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_IS_SIMPLE_SHOW
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    private String specIsSimpleShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_SIMPLE_SHOW_INDEX
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    private BigDecimal specSimpleShowIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_SPEC_TEMPLATE.IS_LONG_TXT
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    private String isLongTxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_SPEC_TEMPLATE.IS_ENABLE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    private String isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_CODE
     *
     * @return the value of ZC_GOODS_SPEC_TEMPLATE.SPEC_CODE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public String getSpecCode() {
        return specCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_CODE
     *
     * @param specCode the value for ZC_GOODS_SPEC_TEMPLATE.SPEC_CODE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public void setSpecCode(String specCode) {
        this.specCode = specCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_NAME
     *
     * @return the value of ZC_GOODS_SPEC_TEMPLATE.SPEC_NAME
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public String getSpecName() {
        return specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_NAME
     *
     * @param specName the value for ZC_GOODS_SPEC_TEMPLATE.SPEC_NAME
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public void setSpecName(String specName) {
        this.specName = specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_PARENT_CODE
     *
     * @return the value of ZC_GOODS_SPEC_TEMPLATE.SPEC_PARENT_CODE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public String getSpecParentCode() {
        return specParentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_PARENT_CODE
     *
     * @param specParentCode the value for ZC_GOODS_SPEC_TEMPLATE.SPEC_PARENT_CODE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public void setSpecParentCode(String specParentCode) {
        this.specParentCode = specParentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_SHOW_INDEX
     *
     * @return the value of ZC_GOODS_SPEC_TEMPLATE.SPEC_SHOW_INDEX
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public BigDecimal getSpecShowIndex() {
        return specShowIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_SHOW_INDEX
     *
     * @param specShowIndex the value for ZC_GOODS_SPEC_TEMPLATE.SPEC_SHOW_INDEX
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public void setSpecShowIndex(BigDecimal specShowIndex) {
        this.specShowIndex = specShowIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_IS_SIMPLE_SHOW
     *
     * @return the value of ZC_GOODS_SPEC_TEMPLATE.SPEC_IS_SIMPLE_SHOW
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public String getSpecIsSimpleShow() {
        return specIsSimpleShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_IS_SIMPLE_SHOW
     *
     * @param specIsSimpleShow the value for ZC_GOODS_SPEC_TEMPLATE.SPEC_IS_SIMPLE_SHOW
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public void setSpecIsSimpleShow(String specIsSimpleShow) {
        this.specIsSimpleShow = specIsSimpleShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_SIMPLE_SHOW_INDEX
     *
     * @return the value of ZC_GOODS_SPEC_TEMPLATE.SPEC_SIMPLE_SHOW_INDEX
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public BigDecimal getSpecSimpleShowIndex() {
        return specSimpleShowIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_SPEC_TEMPLATE.SPEC_SIMPLE_SHOW_INDEX
     *
     * @param specSimpleShowIndex the value for ZC_GOODS_SPEC_TEMPLATE.SPEC_SIMPLE_SHOW_INDEX
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public void setSpecSimpleShowIndex(BigDecimal specSimpleShowIndex) {
        this.specSimpleShowIndex = specSimpleShowIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_SPEC_TEMPLATE.IS_LONG_TXT
     *
     * @return the value of ZC_GOODS_SPEC_TEMPLATE.IS_LONG_TXT
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public String getIsLongTxt() {
        return isLongTxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_SPEC_TEMPLATE.IS_LONG_TXT
     *
     * @param isLongTxt the value for ZC_GOODS_SPEC_TEMPLATE.IS_LONG_TXT
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public void setIsLongTxt(String isLongTxt) {
        this.isLongTxt = isLongTxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_SPEC_TEMPLATE.IS_ENABLE
     *
     * @return the value of ZC_GOODS_SPEC_TEMPLATE.IS_ENABLE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_SPEC_TEMPLATE.IS_ENABLE
     *
     * @param isEnable the value for ZC_GOODS_SPEC_TEMPLATE.IS_ENABLE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }
}