package com.ufgov.zc.common.zc.model;

public class ZcGoodsCataToBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_CATA_TO_BRAND.BRAND_CODE
     *
     * @mbggenerated Tue Jan 19 21:45:31 CST 2016
     */
    private String brandCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_CATA_TO_BRAND.GOODS_CATALOG_CODE
     *
     * @mbggenerated Tue Jan 19 21:45:31 CST 2016
     */
    private String goodsCatalogCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_CATA_TO_BRAND.BRAND_CODE
     *
     * @return the value of ZC_GOODS_CATA_TO_BRAND.BRAND_CODE
     *
     * @mbggenerated Tue Jan 19 21:45:31 CST 2016
     */
    public String getBrandCode() {
        return brandCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_CATA_TO_BRAND.BRAND_CODE
     *
     * @param brandCode the value for ZC_GOODS_CATA_TO_BRAND.BRAND_CODE
     *
     * @mbggenerated Tue Jan 19 21:45:31 CST 2016
     */
    public void setBrandCode(String brandCode) {
        this.brandCode = brandCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_CATA_TO_BRAND.GOODS_CATALOG_CODE
     *
     * @return the value of ZC_GOODS_CATA_TO_BRAND.GOODS_CATALOG_CODE
     *
     * @mbggenerated Tue Jan 19 21:45:31 CST 2016
     */
    public String getGoodsCatalogCode() {
        return goodsCatalogCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_CATA_TO_BRAND.GOODS_CATALOG_CODE
     *
     * @param goodsCatalogCode the value for ZC_GOODS_CATA_TO_BRAND.GOODS_CATALOG_CODE
     *
     * @mbggenerated Tue Jan 19 21:45:31 CST 2016
     */
    public void setGoodsCatalogCode(String goodsCatalogCode) {
        this.goodsCatalogCode = goodsCatalogCode;
    }
}