package com.ufgov.zc.common.zc.model;

public class ZcGoodsToSupplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_TO_SUPPLIER.DANWEIGUID
     *
     * @mbggenerated Tue Jan 19 23:09:42 CST 2016
     */
    private String danweiguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_TO_SUPPLIER.GOODS_CODE
     *
     * @mbggenerated Tue Jan 19 23:09:42 CST 2016
     */
    private String goodsCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_TO_SUPPLIER.DANWEIGUID
     *
     * @return the value of ZC_GOODS_TO_SUPPLIER.DANWEIGUID
     *
     * @mbggenerated Tue Jan 19 23:09:42 CST 2016
     */
    public String getDanweiguid() {
        return danweiguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_TO_SUPPLIER.DANWEIGUID
     *
     * @param danweiguid the value for ZC_GOODS_TO_SUPPLIER.DANWEIGUID
     *
     * @mbggenerated Tue Jan 19 23:09:42 CST 2016
     */
    public void setDanweiguid(String danweiguid) {
        this.danweiguid = danweiguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_TO_SUPPLIER.GOODS_CODE
     *
     * @return the value of ZC_GOODS_TO_SUPPLIER.GOODS_CODE
     *
     * @mbggenerated Tue Jan 19 23:09:42 CST 2016
     */
    public String getGoodsCode() {
        return goodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_TO_SUPPLIER.GOODS_CODE
     *
     * @param goodsCode the value for ZC_GOODS_TO_SUPPLIER.GOODS_CODE
     *
     * @mbggenerated Tue Jan 19 23:09:42 CST 2016
     */
    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode;
    }
}