package com.ufgov.zc.common.zc.model;


public class ZcGoodsCatalog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_CATALOG.GOODS_CATALOG_CODE
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    private String goodsCatalogCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_CATALOG.GOODS_CATALOG_NAME
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    private String goodsCatalogName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_CATALOG.SHOW_INDEX
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    private Integer showIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_CATALOG.SPEC_CODE
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    private String specCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_CATALOG.IS_ENABLE
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    private String isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_CATALOG.GOODS_CATALOG_CODE
     *
     * @return the value of ZC_GOODS_CATALOG.GOODS_CATALOG_CODE
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    public String getGoodsCatalogCode() {
        return goodsCatalogCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_CATALOG.GOODS_CATALOG_CODE
     *
     * @param goodsCatalogCode the value for ZC_GOODS_CATALOG.GOODS_CATALOG_CODE
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    public void setGoodsCatalogCode(String goodsCatalogCode) {
        this.goodsCatalogCode = goodsCatalogCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_CATALOG.GOODS_CATALOG_NAME
     *
     * @return the value of ZC_GOODS_CATALOG.GOODS_CATALOG_NAME
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    public String getGoodsCatalogName() {
        return goodsCatalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_CATALOG.GOODS_CATALOG_NAME
     *
     * @param goodsCatalogName the value for ZC_GOODS_CATALOG.GOODS_CATALOG_NAME
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    public void setGoodsCatalogName(String goodsCatalogName) {
        this.goodsCatalogName = goodsCatalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_CATALOG.SHOW_INDEX
     *
     * @return the value of ZC_GOODS_CATALOG.SHOW_INDEX
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    public Integer getShowIndex() {
        return showIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_CATALOG.SHOW_INDEX
     *
     * @param showIndex the value for ZC_GOODS_CATALOG.SHOW_INDEX
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    public void setShowIndex(Integer showIndex) {
        this.showIndex = showIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_CATALOG.SPEC_CODE
     *
     * @return the value of ZC_GOODS_CATALOG.SPEC_CODE
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    public String getSpecCode() {
        return specCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_CATALOG.SPEC_CODE
     *
     * @param specCode the value for ZC_GOODS_CATALOG.SPEC_CODE
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    public void setSpecCode(String specCode) {
        this.specCode = specCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_CATALOG.IS_ENABLE
     *
     * @return the value of ZC_GOODS_CATALOG.IS_ENABLE
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_CATALOG.IS_ENABLE
     *
     * @param isEnable the value for ZC_GOODS_CATALOG.IS_ENABLE
     *
     * @mbggenerated Tue Jan 19 22:16:18 CST 2016
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }
}