package com.ufgov.zc.common.zc.model;

public class ZcGoodsCataToCata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_CATA_TO_CATA.ZC_YEAR
     *
     * @mbggenerated Tue Jan 19 21:59:11 CST 2016
     */
    private String zcYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_CATA_TO_CATA.ZC_CATALOGUE_CODE
     *
     * @mbggenerated Tue Jan 19 21:59:11 CST 2016
     */
    private String zcCatalogueCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_GOODS_CATA_TO_CATA.GOODS_CATALOG_CODE
     *
     * @mbggenerated Tue Jan 19 21:59:11 CST 2016
     */
    private String goodsCatalogCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_CATA_TO_CATA.ZC_YEAR
     *
     * @return the value of ZC_GOODS_CATA_TO_CATA.ZC_YEAR
     *
     * @mbggenerated Tue Jan 19 21:59:11 CST 2016
     */
    public String getZcYear() {
        return zcYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_CATA_TO_CATA.ZC_YEAR
     *
     * @param zcYear the value for ZC_GOODS_CATA_TO_CATA.ZC_YEAR
     *
     * @mbggenerated Tue Jan 19 21:59:11 CST 2016
     */
    public void setZcYear(String zcYear) {
        this.zcYear = zcYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_CATA_TO_CATA.ZC_CATALOGUE_CODE
     *
     * @return the value of ZC_GOODS_CATA_TO_CATA.ZC_CATALOGUE_CODE
     *
     * @mbggenerated Tue Jan 19 21:59:11 CST 2016
     */
    public String getZcCatalogueCode() {
        return zcCatalogueCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_CATA_TO_CATA.ZC_CATALOGUE_CODE
     *
     * @param zcCatalogueCode the value for ZC_GOODS_CATA_TO_CATA.ZC_CATALOGUE_CODE
     *
     * @mbggenerated Tue Jan 19 21:59:11 CST 2016
     */
    public void setZcCatalogueCode(String zcCatalogueCode) {
        this.zcCatalogueCode = zcCatalogueCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_GOODS_CATA_TO_CATA.GOODS_CATALOG_CODE
     *
     * @return the value of ZC_GOODS_CATA_TO_CATA.GOODS_CATALOG_CODE
     *
     * @mbggenerated Tue Jan 19 21:59:11 CST 2016
     */
    public String getGoodsCatalogCode() {
        return goodsCatalogCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_GOODS_CATA_TO_CATA.GOODS_CATALOG_CODE
     *
     * @param goodsCatalogCode the value for ZC_GOODS_CATA_TO_CATA.GOODS_CATALOG_CODE
     *
     * @mbggenerated Tue Jan 19 21:59:11 CST 2016
     */
    public void setGoodsCatalogCode(String goodsCatalogCode) {
        this.goodsCatalogCode = goodsCatalogCode;
    }
}