package com.ufgov.zc.common.zc.model;

public class ZcPProMitemService extends ZcBaseBill {
    /**
   * 
   */
  private static final long serialVersionUID = -1132511401552621961L;
  
  public static final String COL_IS_AGREE="ZC_P_PRO_MITEM_SERVICE_IS_AGREE"; // 是否同意
  public static final String COL_SERVICE_CODE="ZC_P_PRO_MITEM_SERVICE_SERVICE_CODE"; // 明细号
  public static final String COL_SERVICE_CONTENT="ZC_P_PRO_MITEM_SERVICE_SERVICE_CONTENT"; // 明细内容
  public static final String COL_SU_CODE="ZC_P_PRO_MITEM_SERVICE_SU_CODE"; // 供应商编号
  public static final String COL_ZC_MAKE_CODE="ZC_P_PRO_MITEM_SERVICE_ZC_MAKE_CODE"; // 计划编号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_P_PRO_MITEM_SERVICE.ZC_MAKE_CODE
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    private String zcMakeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_P_PRO_MITEM_SERVICE.SERVICE_CODE
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    private String serviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_P_PRO_MITEM_SERVICE.SERVICE_CONTENT
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    private String serviceContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_P_PRO_MITEM_SERVICE.SU_CODE
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    private String suCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_P_PRO_MITEM_SERVICE.IS_AGREE
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    private String isAgree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_P_PRO_MITEM_SERVICE.ZC_MAKE_CODE
     *
     * @return the value of ZC_P_PRO_MITEM_SERVICE.ZC_MAKE_CODE
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    public String getZcMakeCode() {
        return zcMakeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_P_PRO_MITEM_SERVICE.ZC_MAKE_CODE
     *
     * @param zcMakeCode the value for ZC_P_PRO_MITEM_SERVICE.ZC_MAKE_CODE
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    public void setZcMakeCode(String zcMakeCode) {
        this.zcMakeCode = zcMakeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_P_PRO_MITEM_SERVICE.SERVICE_CODE
     *
     * @return the value of ZC_P_PRO_MITEM_SERVICE.SERVICE_CODE
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_P_PRO_MITEM_SERVICE.SERVICE_CODE
     *
     * @param serviceCode the value for ZC_P_PRO_MITEM_SERVICE.SERVICE_CODE
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_P_PRO_MITEM_SERVICE.SERVICE_CONTENT
     *
     * @return the value of ZC_P_PRO_MITEM_SERVICE.SERVICE_CONTENT
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    public String getServiceContent() {
        return serviceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_P_PRO_MITEM_SERVICE.SERVICE_CONTENT
     *
     * @param serviceContent the value for ZC_P_PRO_MITEM_SERVICE.SERVICE_CONTENT
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    public void setServiceContent(String serviceContent) {
        this.serviceContent = serviceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_P_PRO_MITEM_SERVICE.SU_CODE
     *
     * @return the value of ZC_P_PRO_MITEM_SERVICE.SU_CODE
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    public String getSuCode() {
        return suCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_P_PRO_MITEM_SERVICE.SU_CODE
     *
     * @param suCode the value for ZC_P_PRO_MITEM_SERVICE.SU_CODE
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    public void setSuCode(String suCode) {
        this.suCode = suCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_P_PRO_MITEM_SERVICE.IS_AGREE
     *
     * @return the value of ZC_P_PRO_MITEM_SERVICE.IS_AGREE
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    public String getIsAgree() {
        return isAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_P_PRO_MITEM_SERVICE.IS_AGREE
     *
     * @param isAgree the value for ZC_P_PRO_MITEM_SERVICE.IS_AGREE
     *
     * @mbggenerated Sun Feb 14 09:27:59 CST 2016
     */
    public void setIsAgree(String isAgree) {
        this.isAgree = isAgree;
    }
}