package com.ufgov.zc.server.zc.dao;

import java.util.List;

import com.ufgov.zc.common.system.dto.ElementConditionDto;
import com.ufgov.zc.common.zc.model.ZcBrand;

public interface ZcBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_BRAND
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    int deleteByPrimaryKey(String brandCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_BRAND
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    int insert(ZcBrand record);
 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_BRAND
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    ZcBrand selectByPrimaryKey(String brandCode);
 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_BRAND
     *
     * @mbggenerated Tue Jan 19 21:07:25 CST 2016
     */
    int updateByPrimaryKey(ZcBrand record);

    List getMainDataLst(ElementConditionDto elementConditionDto);
}