package com.ufgov.zc.server.zc.dao;

import com.ufgov.zc.common.zc.model.ZcGoodsCataToCata;

public interface ZcGoodsCataToCataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_CATA_TO_CATA
     *
     * @mbggenerated Tue Jan 19 21:59:11 CST 2016
     */
    int insert(ZcGoodsCataToCata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_CATA_TO_CATA
     *
     * @mbggenerated Tue Jan 19 21:59:11 CST 2016
     */
    int insertSelective(ZcGoodsCataToCata record);
}