package com.ufgov.zc.server.zc.dao;

import com.ufgov.zc.common.zc.model.ZcGoodsToSupplier;

public interface ZcGoodsToSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_TO_SUPPLIER
     *
     * @mbggenerated Tue Jan 19 23:09:42 CST 2016
     */
    int insert(ZcGoodsToSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_TO_SUPPLIER
     *
     * @mbggenerated Tue Jan 19 23:09:42 CST 2016
     */
    int insertSelective(ZcGoodsToSupplier record);
}