package com.ufgov.zc.server.zc.dao;

import com.ufgov.zc.common.zc.model.ZcGoodsCataToBrand;

public interface ZcGoodsCataToBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_CATA_TO_BRAND
     *
     * @mbggenerated Tue Jan 19 21:45:31 CST 2016
     */
    int insert(ZcGoodsCataToBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_CATA_TO_BRAND
     *
     * @mbggenerated Tue Jan 19 21:45:31 CST 2016
     */
    int insertSelective(ZcGoodsCataToBrand record);
}