package com.ufgov.zc.server.zc.dao;

import com.ufgov.zc.common.zc.model.ZcGoodsSpecTemplate;

public interface ZcGoodsSpecTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_SPEC_TEMPLATE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    int deleteByPrimaryKey(String specCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_SPEC_TEMPLATE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    int insert(ZcGoodsSpecTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_SPEC_TEMPLATE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    int insertSelective(ZcGoodsSpecTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_SPEC_TEMPLATE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    ZcGoodsSpecTemplate selectByPrimaryKey(String specCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_SPEC_TEMPLATE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    int updateByPrimaryKeySelective(ZcGoodsSpecTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_SPEC_TEMPLATE
     *
     * @mbggenerated Tue Jan 19 23:01:34 CST 2016
     */
    int updateByPrimaryKey(ZcGoodsSpecTemplate record);
}