package com.ufgov.zc.server.zc.dao;

import com.ufgov.zc.common.zc.model.ZcGoodsImage;

public interface ZcGoodsImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_IMAGE
     *
     * @mbggenerated Tue Jan 19 22:27:56 CST 2016
     */
    int deleteByPrimaryKey(String goodsCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_IMAGE
     *
     * @mbggenerated Tue Jan 19 22:27:56 CST 2016
     */
    int insert(ZcGoodsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_IMAGE
     *
     * @mbggenerated Tue Jan 19 22:27:56 CST 2016
     */
    int insertSelective(ZcGoodsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_IMAGE
     *
     * @mbggenerated Tue Jan 19 22:27:56 CST 2016
     */
    ZcGoodsImage selectByPrimaryKey(String goodsCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_IMAGE
     *
     * @mbggenerated Tue Jan 19 22:27:56 CST 2016
     */
    int updateByPrimaryKeySelective(ZcGoodsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_IMAGE
     *
     * @mbggenerated Tue Jan 19 22:27:56 CST 2016
     */
    int updateByPrimaryKey(ZcGoodsImage record);
}