package com.ufgov.zc.server.zc.dao;

import com.ufgov.zc.common.zc.model.ZcGoodsSpec;
import com.ufgov.zc.common.zc.model.ZcGoodsSpecKey;

public interface ZcGoodsSpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_SPEC
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    int deleteByPrimaryKey(ZcGoodsSpecKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_SPEC
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    int insert(ZcGoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_SPEC
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    int insertSelective(ZcGoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_SPEC
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    ZcGoodsSpec selectByPrimaryKey(ZcGoodsSpecKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_SPEC
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    int updateByPrimaryKeySelective(ZcGoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_GOODS_SPEC
     *
     * @mbggenerated Tue Jan 19 22:44:13 CST 2016
     */
    int updateByPrimaryKey(ZcGoodsSpec record);
}